parfumier/reviews/routes.py
"""Imports from Flask, the database and needed forms"""
from datetime import datetime
from flask import flash, redirect, Blueprint, url_for, request, render_template
from flask_login import login_required, current_user
from bson.objectid import ObjectId
from parfumier import mongo
from parfumier.reviews.forms import AddReviewForm, EditReviewForm


reviews = Blueprint("reviews", __name__)


@reviews.route("/perfume/review/<perfume_id>", methods=["POST", "GET"])
@login_required
def review_perfume(perfume_id):
    """Route used to create a review

    After defining all objects to be passed to the template (including
    the cursor with the aggregated perfume) the method updates the array
    of objects in the perfumes collection with the corresponding review.
    It records who posted the review (including a link to their avatar),
    the date of the review and the content with the html produced by
    CKEditor from the text area field.
    The id of the review is created using ObjectId with the current
    creation moment, assigning a virtually unique id to each review.
    """

    form = AddReviewForm()
    form_edit = EditReviewForm()
    perfume = mongo.db.perfumes.find_one({"_id": ObjectId(perfume_id)})
    cur = mongo.db.perfumes.aggregate(
        [
            {
                "$lookup": {
                    "from": "users",
                    "localField": "author",
                    "foreignField": "username",
                    "as": "creator",
                }
            },
            {"$unwind": "$creator"},
            {
                "$project": {
                    "_id": "$_id",
                    "perfumeName": "$name",
                    "perfumeBrand": "$brand",
                    "perfumeDescription": "$description",
                    "date_updated": "$date_updated",
                    "perfumePicture": "$picture",
                    "isPublic": "$public",
                    "perfumeType": "$perfume_type",
                    "username": "$creator.username",
                    "firstName": "$creator.first_name",
                    "lastName": "$creator.last_name",
                    "profilePicture": "$creator.avatar",
                }
            },
            {"$match": {"_id": ObjectId(perfume_id)}},
        ]
    )
    if form.validate_on_submit():
        review_id = ObjectId.from_datetime(datetime.utcnow())
        mongo.db.perfumes.update(
            {"_id": perfume["_id"]},
            {
                "$push": {
                    "reviews": {
                        "_id": review_id,
                        "review_content": form.review.data,
                        "reviewer": current_user.username,
                        "date_reviewed": datetime.utcnow(),
                        "reviewer_picture": current_user.avatar,
                    }
                }
            },
        )
        flash("Your review has been received", "success")
        return redirect(url_for("perfumes.perfume", perfume_id=perfume["_id"]))
    return render_template(
        "pages/perfume.html",
        perfume=perfume,
        add_review_form=form,
        edit_review_form=form_edit,
        cursor=cur,
        title="Perfume"
    )


@reviews.route("/perfume/review", methods=["POST"])
@login_required
def delete_review():
    """Deletes a particular review

    This simply deletes a review based on the combination of
    the id from both the perfume and the review itself.
    As this comes from a modal, that information is passed
    through the hidden inputs in the modal, from the main
    corresponding template.
    """

    review_id = request.form.get("review_id")
    perfume_id = request.form.get("perfume_id")
    mongo.db.perfumes.update_one(
        {"_id": ObjectId(perfume_id)},
        {"$pull": {"reviews": {"_id": ObjectId(review_id)}}},
    )
    flash("Your review has been deleted!", "success")
    return redirect(url_for("perfumes.perfume", perfume_id=perfume_id))


@reviews.route("/review", methods=["GET", "POST"])
@login_required
def edit_review():
    """Edits an existing review

    Similar to the previous method, this one also collects the necessary
    identificators from the hidden fields containing the ids passed from
    the main template.
    It then simply updates the existing review.
    A JavaScript function pre-populates the form displaying the current
    contents of the review to be modified.
    """

    form = EditReviewForm()
    review_id = request.form.get("review_id")
    perfume_id = request.form.get("perfume_id")
    if form.validate_on_submit():
        mongo.db.perfumes.update(
            {"_id": ObjectId(perfume_id), "reviews._id": ObjectId(review_id)},
            {"$set": {"reviews.$.review_content": form.edit_review.data, }},
        )
        flash("Your review has been updated!", "success")
        return redirect(url_for("perfumes.perfume", perfume_id=perfume_id))
    flash("Your review has not been changed", "danger")
    return redirect(url_for("perfumes.perfume", perfume_id=perfume_id))

parfumier/types/routes.py
"""Imports all Flask components, database object and forms"""
from flask import Blueprint, redirect, url_for, render_template, flash, request
from flask_login import current_user, login_required
from cloudinary.uploader import upload
from cloudinary.utils import cloudinary_url
from bson.objectid import ObjectId
from parfumier import mongo
from parfumier.types.forms import CreateTypeForm, EditTypeForm
from flask_paginate import Pagination, get_page_parameter


types = Blueprint("types", __name__)


@types.route("/type/new", methods=["POST", "GET"])
@login_required
def new_type():
    """Creates a new Perfume Type

    User has to be an admin in order to create a perfume type.
    The route simply creates a new document with the information
    passed in the form in case the form validates.
    """

    if current_user.is_admin:
        form = CreateTypeForm()
        if form.validate_on_submit():
            if form.type_picture.data:
                picture_uploaded = upload(form.type_picture.data)
                type_picture, options = cloudinary_url(
                    picture_uploaded["public_id"],
                    format="jpg",
                    crop="fill",
                    width=250,
                    height=250,
                    opacity=20,
                )
                picture_link = type_picture.replace("http", "https")
                mongo.db.types.insert(
                    {
                        "type_name": form.type_name.data,
                        "description": form.description.data,
                        "type_picture": picture_link,
                        "author": current_user.username,
                    }
                )
            else:
                mongo.db.types.insert(
                    {
                        "type_name": form.type_name.data,
                        "description": form.description.data,
                        "type_picture": (
                            "https://res.cloudinary.com/gbrachetta/"
                            "image/upload/c_scale,o_20,w_293/"
                            "v1578262574/sample.jpg"
                        ),
                        "author": current_user.username,
                    }
                )
            flash("You added a new type!", "info")
            return redirect(url_for("types.all_types"))
    else:
        flash("You need to be an administrator.", "danger")
        return redirect(url_for("main.index"))
    return render_template(
        "pages/perfume-and-type.html",
        title="New Type",
        form=form,
        new_type=True,
        heading="New Type",
    )


@types.route("/types")
def all_types():
    """Displays all types

    This route simply displays all existing types.
    It uses aggregation in order to allow for pagination.
    """
    page = request.args.get(get_page_parameter(), type=int, default=1)
    total_types = mongo.db.types.find().count()
    page_count = 8
    the_types = mongo.db.types.aggregate(
        [
            {
                "$lookup": {
                    "from": "types",
                    "localField": "type_name",
                    "foreignField": "perfume_type",
                    "as": "type",
                }
            },
            {"$unwind": "$type_name"},
            {
                "$project": {
                    "_id": "$_id",
                    "typeName": "$type_name",
                    "picture": "$type_picture",
                }
            },
            {"$sort": {"typeName": 1}},
            {"$skip": (page - 1) * page_count},
            {"$limit": page_count},
        ]
    )
    pagination = Pagination(
        per_page=8,
        page=page,
        total=total_types,
        record_name="types",
        bs_version=4,
        alignment="center",
        display_msg="Displaying <b>{start} - {end}</b>\
        {record_name} of <b>{total}</b>",
    )
    return render_template(
        "pages/types.html",
        types=the_types,
        title="Types",
        pagination=pagination,
    )


@types.route("/type/<type_id>")
def show_type(type_id):
    """Displays one type only

    This route displays the type selected using the unique ObjectId.
    """

    one_type = mongo.db.types.find_one({"_id": ObjectId(type_id)})
    return render_template(
        "pages/type.html", type=one_type, title=one_type["type_name"]
    )


@types.route("/type/<type_id>", methods=["POST"])
@login_required
def delete_type(type_id):
    """Deletes a perfume type

    This route simply deletes a perfume type matched by its id.
    It's only available to admins.
    """

    if current_user.is_admin:
        mongo.db.types.delete_one({"_id": ObjectId(type_id)})
        flash("You deleted this type", "success")
        return redirect(url_for("types.all_types"))
    flash("Not allowed", "warning")
    return redirect(url_for("types.all_types"))


@types.route("/type/edit/<type_id>", methods=["POST", "GET"])
@login_required
def edit_type(type_id):
    """Allows editing a Perfume Type

    This route finds a type by its id, assigns the current name to the hidden
    field (used to check against to avoid a false validation error) and updates
    the current data from its corresponding document in the database.
    """

    form = EditTypeForm()
    current_type = mongo.db.types.find_one({"_id": ObjectId(type_id)})
    current_type_name = mongo.db.types.find_one(
        {"_id": ObjectId(type_id)}, {"_id": 0, "type_name": 1}
    )
    form.origin_type_name.data = current_type_name["type_name"]
    current_type_value = mongo.db.types.find_one({"_id": ObjectId(type_id)})
    if current_user.is_admin:
        if form.validate_on_submit():
            if form.type_picture.data:
                picture_uploaded = upload(form.type_picture.data)
                type_picture, options = cloudinary_url(
                    picture_uploaded["public_id"],
                    format="jpg",
                    crop="fill",
                    width=250,
                    height=250,
                    opacity=20,
                )
                picture_link = type_picture.replace("http", "https")
                new_value = {
                    "$set": {
                        "type_name": form.type_name.data,
                        "description": form.description.data,
                        "type_picture": picture_link,
                    }
                }
                mongo.db.types.update_one(current_type_value, new_value)
                flash("Type has been updated", "info")
                return redirect(
                    url_for(
                        "types.show_type", type_id=current_type_value["_id"]
                    )
                )
            else:
                new_value = {
                    "$set": {
                        "type_name": form.type_name.data,
                        "description": form.description.data,
                    }
                }
            mongo.db.types.update_one(current_type_value, new_value)
            flash("Type has been updated", "info")
            return redirect(
                url_for("types.show_type", type_id=current_type_value["_id"])
            )
        form.type_name.data = current_type_value["type_name"]
        form.description.data = current_type_value["description"]
    return render_template(
        "pages/perfume-and-type.html",
        title="Edit Type",
        form=form,
        current_type=current_type,
        edit_type=True,
        heading="Edit Type",
    )

parfumier/templates/modals/about-me.html
<!-- About me modal -->
<div class="modal fade" id="aboutModal" tabindex="-1" role="dialog" aria-labelledby="modal-about-label"
    aria-hidden="true">
    <div class="modal-dialog modal-md" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modal-about-label">About me</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body text-center">
                <h3 class="heading-modal">Guillermo Brachetta</h3>
                <img src="{{ url_for("static", filename="images/avatar.png") }}" loading="lazy" width="500" height="500"
                    alt="avatar" class="img-fluid my-3" />
                <p class="text-left">
                    I'm driven by the senses.<br />All that touches me, moves me.<br />A Haydn
                    string quartet, the taste and texture of oysters, the view of a 15th century
                    cathedral or the fragrance of a sophisticated perfume they all elevate me in a
                    similar way.<br /><br />This is my contribution to the world of scents.
                </p>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-sm my-buttons purple mt-0" data-dismiss="modal">
                    Close
                </button>
            </div>
        </div>
    </div>
</div>

parfumier/templates/modals/create-review-modal.html
<!-- Create review MODAL -->
<div class="modal fade" role="dialog" tabindex="-1" id="reviewPerfumeModal" aria-labelledby="reviewPerfumeModalLabel"
    aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Please leave a review</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <form method=POST action="{{ url_for("reviews.review_perfume", perfume_id=perfume._id) }}" id="form-review"
                class="shadow-none" novalidate>
                <div class="modal-body">
                    {{ add_review_form.hidden_tag() }}
                    <div class="form-group">
                        {% if add_review_form.review.errors %}
                        {{ add_review_form.review(class="form-control form-control-md is-invalid ckeditor") }}
                        <div class="invalid-feedback">
                            {% for error in add_review_form.review.errors %}
                            <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                        {% else %}
                        {{ add_review_form.review(class="form-control form-control-md ckeditor", placeholder="Review") }}
                        {% endif %}
                    </div>
                </div>
                <div class="modal-footer">
                    <div class="form-group">
                        {{ add_review_form.submit(class="btn btn-sm shadow-sm btn-sm my-buttons blue") }}
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

parfumier/templates/modals/delete-perfume-modal.html
<!-- Delete perfume MODAL -->
<div class="modal fade" role="dialog" tabindex="-1" id="deletePerfumeModal" aria-labelledby="deletePerfumeModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Please&nbsp;Confirm</h4><button type="button" class="close" data-dismiss="modal"
                    aria-label="Close"><span aria-hidden="true">×</span></button>
            </div>
            <div class="modal-body">
                <p>Please confirm that you want to delete this perfume: {{ perfume.name }}.</p>
                <p class="warning-modals">This action cannot be undone.</p>
            </div>
            <div class="modal-footer">
                <form action="{{ url_for("perfumes.delete_perfume", perfume_id=perfume._id) }}" method="POST">
                    <input type="submit" , class="btn btn-sm shadow-sm my-buttons red" value="Delete">
                </form>
            </div>
        </div>
    </div>
</div>

parfumier/templates/modals/delete-review-modal.html
<!-- Delete review MODAL -->
<div class="modal fade" role="dialog" tabindex="-1" id="deleteReviewModal" aria-labelledby="deleteReviewModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Please&nbsp;Confirm</h4><button type="button" class="close" data-dismiss="modal"
                    aria-label="Close"><span aria-hidden="true">×</span></button>
            </div>
            <div class="modal-body">
                <p>Please confirm that you want to delete this review.</p>
                <p class="warning-modals">This action cannot be undone.</p>
            </div>
            <div class="modal-footer">
                <form id="form-delete-review" action="{{ url_for("reviews.delete_review") }}" method="POST">
                    <input hidden name="review_id">
                    <input hidden name="perfume_id">
                    <input type="submit" class="btn btn-sm shadow-sm my-buttons red" value="Delete">
                </form>
            </div>
        </div>
    </div>
</div>

parfumier/templates/modals/delete-type-modal.html
<!-- Delete type modal -->
<div class="modal fade" id="deleteTypeModal" tabindex="-1" role="dialog" aria-labelledby="deleteTypeModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Please Confirm</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Please confirm you want to delete this type: {{ type.type_name }}.</p>
                <p class="warning-modals">This action cannot be undone.</p>
            </div>
            <div class="modal-footer">
                <form action="{{ url_for("types.delete_type", type_id=type._id) }}" method="POST">
                    <input type="submit" , class="btn  btn-sm shadow-sm my-buttons red" value="Delete">
                </form>
            </div>
        </div>
    </div>
</div

parfumier/templates/modals/delete-user-modal.html
<!-- Delete user modal -->
<div class="modal fade" id="deleteUserModal" tabindex="-1" role="dialog" aria-labelledby="deleteUserModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Please Confirm</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <p>You are about to delete your account.</p>
                <p class="warning-modals">This action cannot be undone.</p>
            </div>
            <div class="modal-footer">
                <form action="{{ url_for("users.delete_user") }}" method="POST">
                    <input type="submit" , class="btn btn-sm shadow-sm my-buttons red" value="Delete">
                </form>
            </div>
        </div>
    </div>

parfumier/templates/modals/edit-review-modal.html
<!-- Edit Review modal -->
<div class="modal fade" role="dialog" tabindex="-1" id="editReviewPerfumeModal"
    aria-labelledby="editReviewPerfumeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Edit your review</h4><button type="button" class="close" data-dismiss="modal"
                    aria-label="Close"><span aria-hidden="true">×</span></button>
            </div>
            <div class="modal-body">
                <form class="shadow-none" method=POST action="{{ url_for("reviews.edit_review") }}"
                    id="form-edit-review">
                    {{ edit_review_form.hidden_tag() }}
                    <fieldset class="form-group">
                        <div class="form-group">
                            {% if edit_review_form.edit_review.errors %}
                            {{ edit_review_form.edit_review(class="form-control form-control-md ckeditor is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in edit_review_form.edit_review.errors %}
                                <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                            {% else %}
                            {{ edit_review_form.edit_review(class="form-control form-control-md ckeditor", placeholder="Review") }}
                            {% endif %}
                        </div>
                    </fieldset>
                    <div class="modal-footer pr-0 pb-0">
                        <div class="form-group">
                            <input hidden name="review_id">
                            <input hidden name="perfume_id">
                            {{ edit_review_form.submit(class="btn btn-sm shadow-sm btn-sm my-buttons blue") }}
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

parfumier/templates/modals/login-reminder-modal.html
<!-- Login reminder modal -->
<div class="modal fade" role="dialog" tabindex="-1" id="loginReminderModal" aria-labelledby="loginReminderModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modal-about-label">Log in</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p class="mb-0">You must be registered and logged in to perform this action.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-sm my-buttons purple mt-0" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>