parfumier/perfumes/routes.py
"""Besides the flask imports, datetime to stamp current creation date,
cloudinary_url and upload to deal with uploading images and ObjectId to
find and deal with objects by their id.
"""
from datetime import datetime
from flask import render_template, redirect, flash, url_for, request, Blueprint
from flask_login import login_required, current_user
from cloudinary.uploader import upload
from cloudinary.utils import cloudinary_url
from bson.objectid import ObjectId
from parfumier.perfumes.forms import CreatePerfumeForm, EditPerfumeForm
from parfumier.reviews.forms import AddReviewForm, EditReviewForm
from parfumier import mongo
from flask_paginate import Pagination, get_page_parameter

perfumes = Blueprint("perfumes", __name__)


@perfumes.route("/perfumes")
def all_perfumes():
    """Displays all pefumes

    With a solution found on my question on Stack Overflow:
    https://stackoverflow.com/questions/61732985/inner-join-like-with-mongodb-in-flask-jinja
    Adds pagination (8 items per page) and uses aggregation to
    combine multiple collections.
    Returns a cursor with the said aggregation amongst pagination objects
    and the types collection ordered by name.
    """
    page = request.args.get(get_page_parameter(), type=int, default=1)
    types = mongo.db.types.find().sort("type_name")
    page_count = 8
    total_perfumes = mongo.db.perfumes.count()
    pagination = Pagination(
        per_page=8,
        page=page,
        total=total_perfumes,
        record_name="perfumes",
        bs_version=4,
        alignment="center",
        display_msg="Displaying <b>{start} - {end}</b>\
             {record_name} of <b>{total}</b>",
    )
    cur = mongo.db.perfumes.aggregate(
        [
            {
                "$lookup": {
                    "from": "users",
                    "localField": "author",
                    "foreignField": "username",
                    "as": "creator",
                }
            },
            {"$unwind": "$creator"},
            {
                "$project": {
                    "_id": "$_id",
                    "perfumeName": "$name",
                    "perfumeBrand": "$brand",
                    "perfumeDescription": "$description",
                    "date_updated": "$date_updated",
                    "perfumePicture": "$picture",
                    "isPublic": "$public",
                    "perfumeType": "$perfume_type",
                    "username": "$creator.username",
                    "firstName": "$creator.first_name",
                    "lastName": "$creator.last_name",
                    "profilePicture": "$creator.avatar",
                }
            },
            {"$sort": {"perfumeName": 1}},
            {"$skip": (page - 1) * page_count},
            {"$limit": page_count},
        ]
    )
    return render_template(
        "pages/perfumes.html",
        title="Perfumes",
        perfumes=cur,
        types=types,
        pagination=pagination,
    )


@perfumes.route("/perfume/new", methods=["GET", "POST"])
@login_required
def new_perfume():
    """Creates a new perfume (only admins)

    Uses Cloudinary to upload images. The variable 'options' throws a
    warning but it's necessary to specify Cloudinary's settings.
    In case a picture isn't chosen, the function defaults to a
    pre-chosen generic photo present in Cloudinary.
    """

    if current_user.is_admin:
        form = CreatePerfumeForm()
        if form.validate_on_submit():
            if form.picture.data:
                picture_uploaded = upload(form.picture.data)
                picture, options = cloudinary_url(
                    picture_uploaded["public_id"],
                    format="jpg",
                    crop="fill",
                    width=225,
                    height=300,
                )
                picture_link = picture.replace("http", "https")
                mongo.db.perfumes.insert(
                    {
                        "author": current_user.username,
                        "brand": form.brand.data,
                        "name": form.name.data,
                        "perfume_type": form.perfume_type.data,
                        "description": form.description.data,
                        "date_updated": datetime.utcnow(),
                        "public": form.public.data,
                        "picture": picture_link,
                    }
                )
            else:
                mongo.db.perfumes.insert(
                    {
                        "author": current_user.username,
                        "brand": form.brand.data,
                        "name": form.name.data,
                        "perfume_type": form.perfume_type.data,
                        "description": form.description.data,
                        "date_updated": datetime.utcnow(),
                        "public": form.public.data,
                        "picture": (
                            "https://res.cloudinary.com/gbrachetta/"
                            "image/upload/v1590013198/generic.jpg"
                        ),
                    }
                )

            flash("You added a new perfume!", "info")
            return redirect(url_for("perfumes.all_perfumes"))
    else:
        flash("You need to be an administrator to enter data.", "danger")
        return redirect(url_for("main.index"))
    return render_template(
        "pages/perfume-and-type.html",
        title="New Perfume",
        form=form,
        types=mongo.db.types.find().sort("type_name"),
        new_perfume=True,
        heading="New Perfume",
    )


@perfumes.route("/perfume/<perfume_id>", methods=["GET"])
def perfume(perfume_id):
    """Returns an individual perfume

    Uses aggregation to combine perfumes and types in order
    to display details about a particular perfume.
    Includes the review form in order to allow for reviews
    to be placed over those individual perfumes.
    """

    current_perfume = mongo.db.perfumes.find_one({"_id": ObjectId(perfume_id)})
    add_review_form = AddReviewForm()
    edit_review_form = EditReviewForm()
    cur = mongo.db.perfumes.aggregate(
        [
            {
                "$lookup": {
                    "from": "users",
                    "localField": "author",
                    "foreignField": "username",
                    "as": "creator",
                }
            },
            {"$unwind": "$creator"},
            {
                "$project": {
                    "_id": "$_id",
                    "perfumeName": "$name",
                    "perfumeBrand": "$brand",
                    "perfumeDescription": "$description",
                    "date_updated": "$date_updated",
                    "perfumePicture": "$picture",
                    "isPublic": "$public",
                    "perfumeType": "$perfume_type",
                    "username": "$creator.username",
                    "firstName": "$creator.first_name",
                    "lastName": "$creator.last_name",
                    "profilePicture": "$creator.avatar",
                }
            },
            {"$match": {"_id": ObjectId(perfume_id)}},
        ]
    )
    return render_template(
        "pages/perfume.html",
        title=current_perfume["name"],
        cursor=cur,
        perfume=current_perfume,
        add_review_form=add_review_form,
        edit_review_form=edit_review_form,
    )


@perfumes.route("/perfume/<perfume_id>/delete", methods=["POST", "GET"])
@login_required
def delete_perfume(perfume_id):
    """Deletes a perfume

    Simply deletes one perfume found through its ObjectId.
    """

    if current_user.is_admin:
        mongo.db.perfumes.delete_one({"_id": ObjectId(perfume_id)})
        flash("You deleted this perfume", "success")
        return redirect(url_for("perfumes.all_perfumes"))
    flash("Not allowed", "warning")
    return redirect(url_for("perfumes.all_perfumes"))


@perfumes.route("/perfume/edit/<perfume_id>", methods=["POST", "GET"])
@login_required
def edit_perfume(perfume_id):
    """Edits an existing perfume

    If the user is an admin and the form validates, checks if there is a
    picture to be uploaded, in which case it uses the cloudinary import
    with its options to format and resize it.
    The function also replaces the http protocol rendered by cloudinary
    with https to serve them securely.
    It then updates the existing record. This existing record populates
    the form with its current values.
    """

    form = EditPerfumeForm()
    current_perfume = mongo.db.perfumes.find_one({"_id": ObjectId(perfume_id)})
    if current_user.is_admin:
        if form.validate_on_submit():
            if form.picture.data:
                picture_uploaded = upload(form.picture.data)
                # "options" is a needed parameter in order for cloudinary to
                # format the thumbnail server-side
                picture, options = cloudinary_url(
                    picture_uploaded["public_id"],
                    format="jpg",
                    crop="fill",
                    width=225,
                    height=300,
                )
                picture_link = picture.replace("http", "https")
                new_value = {
                    "$set": {
                        "brand": form.brand.data,
                        "name": form.name.data,
                        "perfume_type": form.perfume_type.data,
                        "description": form.description.data,
                        "date_updated": datetime.utcnow(),
                        "public": form.public.data,
                        "picture": picture_link,
                    }
                }
                mongo.db.perfumes.update_one(current_perfume, new_value)
                flash("You updated the perfume", "info")
                return redirect(
                    url_for(

parfumier/types/routes.py
"""Imports all Flask components, database object and forms"""
from flask import Blueprint, redirect, url_for, render_template, flash, request
from flask_login import current_user, login_required
from cloudinary.uploader import upload
from cloudinary.utils import cloudinary_url
from bson.objectid import ObjectId
from parfumier import mongo
from parfumier.types.forms import CreateTypeForm, EditTypeForm
from flask_paginate import Pagination, get_page_parameter


types = Blueprint("types", __name__)


@types.route("/type/new", methods=["POST", "GET"])
@login_required
def new_type():
    """Creates a new Perfume Type

    User has to be an admin in order to create a perfume type.
    The route simply creates a new document with the information
    passed in the form in case the form validates.
    """

    if current_user.is_admin:
        form = CreateTypeForm()
        if form.validate_on_submit():
            if form.type_picture.data:
                picture_uploaded = upload(form.type_picture.data)
                type_picture, options = cloudinary_url(
                    picture_uploaded["public_id"],
                    format="jpg",
                    crop="fill",
                    width=250,
                    height=250,
                    opacity=20,
                )
                picture_link = type_picture.replace("http", "https")
                mongo.db.types.insert(
                    {
                        "type_name": form.type_name.data,
                        "description": form.description.data,
                        "type_picture": picture_link,
                        "author": current_user.username,
                    }
                )
            else:
                mongo.db.types.insert(
                    {
                        "type_name": form.type_name.data,
                        "description": form.description.data,
                        "type_picture": (
                            "https://res.cloudinary.com/gbrachetta/"
                            "image/upload/c_scale,o_20,w_293/"
                            "v1578262574/sample.jpg"
                        ),
                        "author": current_user.username,
                    }
                )
            flash("You added a new type!", "info")
            return redirect(url_for("types.all_types"))
    else:
        flash("You need to be an administrator.", "danger")
        return redirect(url_for("main.index"))
    return render_template(
        "pages/perfume-and-type.html",
        title="New Type",
        form=form,
        new_type=True,
        heading="New Type",
    )


@types.route("/types")
def all_types():
    """Displays all types

    This route simply displays all existing types.
    It uses aggregation in order to allow for pagination.
    """
    page = request.args.get(get_page_parameter(), type=int, default=1)
    total_types = mongo.db.types.find().count()
    page_count = 8
    the_types = mongo.db.types.aggregate(
        [
            {
                "$lookup": {
                    "from": "types",
                    "localField": "type_name",
                    "foreignField": "perfume_type",
                    "as": "type",
                }
            },
            {"$unwind": "$type_name"},
            {
                "$project": {
                    "_id": "$_id",
                    "typeName": "$type_name",
                    "picture": "$type_picture",
                }
            },
            {"$sort": {"typeName": 1}},
            {"$skip": (page - 1) * page_count},
            {"$limit": page_count},
        ]
    )
    pagination = Pagination(
        per_page=8,
        page=page,
        total=total_types,
        record_name="types",
        bs_version=4,
        alignment="center",
        display_msg="Displaying <b>{start} - {end}</b>\
        {record_name} of <b>{total}</b>",
    )
    return render_template(
        "pages/types.html",
        types=the_types,
        title="Types",
        pagination=pagination,
    )


@types.route("/type/<type_id>")
def show_type(type_id):
    """Displays one type only

    This route displays the type selected using the unique ObjectId.
    """

    one_type = mongo.db.types.find_one({"_id": ObjectId(type_id)})
    return render_template(
        "pages/type.html", type=one_type, title=one_type["type_name"]
    )


@types.route("/type/<type_id>", methods=["POST"])
@login_required
def delete_type(type_id):
    """Deletes a perfume type

    This route simply deletes a perfume type matched by its id.
    It's only available to admins.
    """

    if current_user.is_admin:
        mongo.db.types.delete_one({"_id": ObjectId(type_id)})
        flash("You deleted this type", "success")
        return redirect(url_for("types.all_types"))
    flash("Not allowed", "warning")
    return redirect(url_for("types.all_types"))


@types.route("/type/edit/<type_id>", methods=["POST", "GET"])
@login_required
def edit_type(type_id):
    """Allows editing a Perfume Type

    This route finds a type by its id, assigns the current name to the hidden
    field (used to check against to avoid a false validation error) and updates
    the current data from its corresponding document in the database.
    """

    form = EditTypeForm()
    current_type = mongo.db.types.find_one({"_id": ObjectId(type_id)})
    current_type_name = mongo.db.types.find_one(
        {"_id": ObjectId(type_id)}, {"_id": 0, "type_name": 1}
    )
    form.origin_type_name.data = current_type_name["type_name"]
    current_type_value = mongo.db.types.find_one({"_id": ObjectId(type_id)})
    if current_user.is_admin:
        if form.validate_on_submit():
            if form.type_picture.data:
                picture_uploaded = upload(form.type_picture.data)
                type_picture, options = cloudinary_url(
                    picture_uploaded["public_id"],
                    format="jpg",
                    crop="fill",
                    width=250,
                    height=250,
                    opacity=20,
                )
                picture_link = type_picture.replace("http", "https")
                new_value = {
                    "$set": {
                        "type_name": form.type_name.data,
                        "description": form.description.data,
                        "type_picture": picture_link,
                    }
                }
                mongo.db.types.update_one(current_type_value, new_value)
                flash("Type has been updated", "info")
                return redirect(
                    url_for(
                        "types.show_type", type_id=current_type_value["_id"]
                    )
                )
            else:
                new_value = {
                    "$set": {
                        "type_name": form.type_name.data,
                        "description": form.description.data,
                    }
                }
            mongo.db.types.update_one(current_type_value, new_value)
            flash("Type has been updated", "info")
            return redirect(
                url_for("types.show_type", type_id=current_type_value["_id"])
            )
        form.type_name.data = current_type_value["type_name"]
        form.description.data = current_type_value["description"]
    return render_template(
        "pages/perfume-and-type.html",
        title="Edit Type",
        form=form,
        current_type=current_type,
        edit_type=True,
        heading="Edit Type",
    )

parfumier/templates/components/buttons-perfume.html
<!-- Logic to display buttons depending on user status -->
{% if current_user.is_admin %}
<div class="col-2 text-center text-sm-left my-3">
    <a class="shadow-sm btn btn-sm my-buttons green" href="{{ url_for("perfumes.all_perfumes") }}">Back</a>
</div>
<div class="col-10 text-right my-3">
    <button class="btn btn-sm shadow-sm my-buttons purple" type="button" data-toggle="modal"
        data-target="#reviewPerfumeModal">Review</button>
    <a class="shadow-sm btn btn-sm my-buttons blue"
        href="{{ url_for("perfumes.edit_perfume", perfume_id=perfume._id) }}" role="button">Edit</a>
    <!-- Hides delete button if admin not the creator of the record -->
    <button {% if current_user.username != perfume.author %}hidden{% endif %} type="button"
        class="btn btn-sm shadow-sm my-buttons red" data-toggle="modal"
        data-target="#deletePerfumeModal">Delete</button>
</div>
{% else %}
<div class="col text-left my-3">
    <a class="shadow-sm btn btn-sm my-buttons green" href="{{ url_for("perfumes.all_perfumes") }}">Back</a>
</div>
<div class="col text-right my-3">
    {% if current_user.is_authenticated %}
    <button class="btn btn-sm shadow-sm my-buttons purple" type="button" data-toggle="modal"
        data-target="#reviewPerfumeModal">Review</button>
    {% else %}
    <button class="btn btn-sm shadow-sm my-buttons purple" type="button" data-toggle="modal"
        data-target="#loginReminderModal">Review</button>
    {% endif %}
</div>
{% endif %}

parfumier/templates/components/perfume-card.html
<div class="row no-gutters justify-content-center">
    {% for perfume in perfumes %}
    {% if perfume %}
    <div class="col-6 col-md-3 item zoom-on-hover">
        <a href="{{ url_for("perfumes.perfume", perfume_id=perfume._id) }}">
            <img class="img-fluid image perfume-picture" src="{{ perfume["perfumePicture"] }}" height="300" width="300"
                loading="lazy" alt="perfume img">
            <div class="description">
                <span class="description-heading">{{ perfume["perfumeName"] }}</span>
                <p class="d-none d-sm-block description-body d-xs-none">
                    Click on the card to find out more</p>
            </div>
        </a>
    </div>
    {% endif %}
    {% else %}
    <!-- Message if no perfume found -->
    <div class="heading">
        <h4>No perfumes matched your query</h4>
    </div>
    {% endfor %}
</div>

parfumier/templates/components/perfume-cursor.html
{% for author in cursor %}
<div class="row">
    <!-- Left Column Perfume - Formatted information -->
    <div class="col-12 col-lg-2 text-center meta left-perfume-container pl-3">
        <div class="text-left tags"><span class="meta-heading">Brand</span>
            <span class="text-info">{{ perfume.brand.title() }}</span>
            <span class="meta-heading">Type of perfume</span>
            <span class="text-info">{{ perfume.perfume_type.title() }}</span>
            <span class="meta-heading">Date Posted</span>
            <span class="text-muted">{{ perfume.date_updated.strftime("%d-%m-%Y") }}</span>
            <span class="meta-heading">Posted by</span>
            <span class="text-info">{{ author["username"].title() }}</span>
            <span class="text-muted">({{ author["firstName"].title() }} {{ author["lastName"].title() }})</span>
        </div>
        <div class="row">
            <div class="col-12 text-left perfume-avatar-container mb-2">
                <img class="rounded-circle img-fluid perfume-avatar user-picture" src="{{ author["profilePicture"] }}"
                    loading="lazy" width=100 height=100 alt="Avatar">
            </div>
        </div>
    </div>
    <!-- Main Content Perfume Column -->
    <div class="col-12 col-md-8 col-lg-7 info">
        <h3>{{ perfume.name.title() }}, by {{ perfume.brand.title() }}</h3>
        <p>{{ perfume.description | safe }}</p>
    </div>
    <!-- Perfume Picture Column -->
    <div class="col-12 col-md-4 col-lg-3 text-center text-md-right align-self-center">
        <img class="perfume-picture" src="{{ perfume.picture }}" loading="lazy" width=225 height=300 alt="Perfume">
    </div>
    <!-- Buttons -->
    {% include "components/buttons-perfume.html" %}
</div>
{% endfor %}

parfumier/templates/components/perfume-reviews.html
<!-- Perfume reviews -->
<div class="row">
    <div class="col perfume-reviews-container mt-4 pt-4">
        <div class=" border-white">
            <h3 class="text-center">Reviews</h3>
        </div>
        <div class="container mt-0">
            <div class="row justify-content-center">
                <div class="col-12">
                    {% for review in perfume.reviews|sort(attribute="date_reviewed", reverse = True) %}
                    {% include "components/review-card.html" %}
                    {% endfor %}
                    {% if not perfume.reviews %}
                    <div class="row portfolio-block py-0">
                        <div class="col-12 my-5 heading">
                            <p class="text-center small">There are no reviews for this perfume.</p>
                        </div>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>

parfumier/templates/components/review-card.html
<div class="card border-white mb-4">
    <div class="row justify-content-center mb-2">
        <div class="col-12 col-md-2 text-lg-center text-xl-right mb-3">
            <img class=" review-avatar rounded-circle img-fluid mr-3 user-picture"
                src="{{ review["reviewer_picture"] }}" loading="lazy" width=100 height=100 alt="avatar">
        </div>
        <div class="review-content col-12 col-md-8 col-lg-6 mb-2">
            <div class="review-in-prefume">
                <p class="mb-2"><span class="name-reviewer">{{review["reviewer"].title() }}</span> said:&nbsp;</p>
                <div class="content-review">{{ review["review_content"] | safe }}
                </div>
                <small class="text-muted">{{ review.date_reviewed.strftime("%d %B, %Y @%-H:%Mh") }}</small>
            </div>
        </div>
        <div class="col-12 col-md-10 col-lg-3 text-lg-center pr-0 mb-2">
            <!-- Only displays to creators of the record -->
            {% if current_user.username == review["reviewer"] %}
            <button type="button" class="btn btn-sm shadow-sm edit-review my-buttons blue mt-2"
                data-perfume_id="{{ perfume["_id"] }}" data-review_id="{{ review["_id"] }}" data-toggle="modal"
                data-target="#editReviewPerfumeModal" id="editFormButton">Edit</button>
            <button class="btn btn-sm shadow-sm delete-review my-buttons red mt-2" data-perfume_id="{{ perfume["_id"] }}"
                data-review_id="{{ review["_id"] }}" type="button" data-toggle="modal"
                data-target="#deleteReviewModal">Delete</button>
            {% endif %}
        </div>
    </div>
</div>

parfumier/templates/components/search-and-filter.html
<div class="heading mb-0">
    <!-- Displays query next to heading if query passed -->
    <h2>Perfumes{% if query %}: {{ query.lower() }}{% endif %}</h2>
    <div class="row">
        <div class="col-md-6">
            <form id="form" action="{{ url_for("perfumes.filters") }}" class="shadow-none pb-0 px-0">
                <div class="form-group shadow-sm">
                    <select class="custom-select border-white shadow-sm" id="filter_query" name="filter_query"
                        aria-label="Filter by Type">
                        <option selected="true" id="option-selected">Filter by type</option>
                        {% for type in types %}
                        <option value="{{ type["type_name"] }}">{{ type["type_name"] }}</option>
                        {% endfor %}
                        <!-- Only admins have access to this option -->
                        {% if current_user.is_admin %}
                        <option value="{{ url_for("types.new_type") }}">Create new type...</option>
                        {% endif %}
                    </select>

                </div>
            </form>
        </div>
        <div class="col-md-6">
            <form class="shadow-none pb-0 px-0 search-form" action="{{ url_for("perfumes.search") }}">
                <div class="form-group shadow-sm">
                    <div class="input-group">
                        <input class="border rounded-0 form-control" type="text" id="db_query" name="db_query"
                            aria-label="Search">
                        <div class="input-group-append">
                            <button class="btn rounded purple mild" type="submit">Search</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

parfumier/templates/components/type-card.html
<div class="container">
    <div class="row">
        {% for type in types %}
        <div class="card col-12 mb-1">
            <div class="card-body">
                <a href="{{ url_for("types.show_type", type_id=type._id) }}">
                    <h5 class="card-title">
                        <span class="lead text-primary font-weight-bold">{{ type.type_name }}</span>
                    </h5>
                    <hr>
                </a>
                <!-- The flag 'safe' renders CKEditor's html correctly -->
                <p class="card-text">{{ type.description | safe }}</p>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

parfumier/templates/components/type-cursor.html
{% for type in types %}
<div class="col-6 col-md-4 col-lg-3">
    <div class="type-background" style="background-image:url('{{ type.picture }}');">
        <!-- Replaces spaces with hyphens and forces lowercase to correctly name class  -->
        <div class="project-card-no-image px-0 text-center type-{{ type.typeName.replace(" ", "-").lower() }}">
            <h3 class="types-names">{{ type.typeName }}</h3>
            <a class="btn btn-sm shadow-sm my-buttons yellow mt-4" role="button"
                href="{{ url_for("types.show_type", type_id=type._id) }}">Read more</a>
            <div class="tags"></div>
        </div>
    </div>
</div>
{% endfor %}

parfumier/templates/components/type-modal.html
<div class="modal fade" id="deleteTypeModal" tabindex="-1" role="dialog" aria-labelledby="deleteTypeModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Please Confirm</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Please confirm you want to delete this type: {{ type.type_name }}.</p>
                <p class="warning-modals">This action cannot be undone.</p>
            </div>
            <div class="modal-footer">
                <form action="{{ url_for("types.delete_type", type_id=type._id) }}" method="POST">
                    <input type="submit" , class="btn  shadow-sm button-red" value="Delete">
                </form>
            </div>
        </div>
    </div>
</div