parfumier/perfumes/routes.py
"""Besides the flask imports, datetime to stamp current creation date,
cloudinary_url and upload to deal with uploading images and ObjectId to
find and deal with objects by their id.
"""
from datetime import datetime
from flask import render_template, redirect, flash, url_for, request, Blueprint
from flask_login import login_required, current_user
from cloudinary.uploader import upload
from cloudinary.utils import cloudinary_url
from bson.objectid import ObjectId
from parfumier.perfumes.forms import CreatePerfumeForm, EditPerfumeForm
from parfumier.reviews.forms import AddReviewForm, EditReviewForm
from parfumier import mongo
from flask_paginate import Pagination, get_page_parameter

perfumes = Blueprint("perfumes", __name__)


@perfumes.route("/perfumes")
def all_perfumes():
    """Displays all pefumes

    With a solution found on my question on Stack Overflow:
    https://stackoverflow.com/questions/61732985/inner-join-like-with-mongodb-in-flask-jinja
    Adds pagination (8 items per page) and uses aggregation to
    combine multiple collections.
    Returns a cursor with the said aggregation amongst pagination objects
    and the types collection ordered by name.
    """
    page = request.args.get(get_page_parameter(), type=int, default=1)
    types = mongo.db.types.find().sort("type_name")
    page_count = 8
    total_perfumes = mongo.db.perfumes.count()
    pagination = Pagination(
        per_page=8,
        page=page,
        total=total_perfumes,
        record_name="perfumes",
        bs_version=4,
        alignment="center",
        display_msg="Displaying <b>{start} - {end}</b>\
             {record_name} of <b>{total}</b>",
    )
    cur = mongo.db.perfumes.aggregate(
        [
            {
                "$lookup": {
                    "from": "users",
                    "localField": "author",
                    "foreignField": "username",
                    "as": "creator",
                }
            },
            {"$unwind": "$creator"},
            {
                "$project": {
                    "_id": "$_id",
                    "perfumeName": "$name",
                    "perfumeBrand": "$brand",
                    "perfumeDescription": "$description",
                    "date_updated": "$date_updated",
                    "perfumePicture": "$picture",
                    "isPublic": "$public",
                    "perfumeType": "$perfume_type",
                    "username": "$creator.username",
                    "firstName": "$creator.first_name",
                    "lastName": "$creator.last_name",
                    "profilePicture": "$creator.avatar",
                }
            },
            {"$sort": {"perfumeName": 1}},
            {"$skip": (page - 1) * page_count},
            {"$limit": page_count},
        ]
    )
    return render_template(
        "pages/perfumes.html",
        title="Perfumes",
        perfumes=cur,
        types=types,
        pagination=pagination,
    )


@perfumes.route("/perfume/new", methods=["GET", "POST"])
@login_required
def new_perfume():
    """Creates a new perfume (only admins)

    Uses Cloudinary to upload images. The variable 'options' throws a
    warning but it's necessary to specify Cloudinary's settings.
    In case a picture isn't chosen, the function defaults to a
    pre-chosen generic photo present in Cloudinary.
    """

    if current_user.is_admin:
        form = CreatePerfumeForm()
        if form.validate_on_submit():
            if form.picture.data:
                picture_uploaded = upload(form.picture.data)
                picture, options = cloudinary_url(
                    picture_uploaded["public_id"],
                    format="jpg",
                    crop="fill",
                    width=225,
                    height=300,
                )
                picture_link = picture.replace("http", "https")
                mongo.db.perfumes.insert(
                    {
                        "author": current_user.username,
                        "brand": form.brand.data,
                        "name": form.name.data,
                        "perfume_type": form.perfume_type.data,
                        "description": form.description.data,
                        "date_updated": datetime.utcnow(),
                        "public": form.public.data,
                        "picture": picture_link,
                    }
                )
            else:
                mongo.db.perfumes.insert(
                    {
                        "author": current_user.username,
                        "brand": form.brand.data,
                        "name": form.name.data,
                        "perfume_type": form.perfume_type.data,
                        "description": form.description.data,
                        "date_updated": datetime.utcnow(),
                        "public": form.public.data,
                        "picture": (
                            "https://res.cloudinary.com/gbrachetta/"
                            "image/upload/v1590013198/generic.jpg"
                        ),
                    }
                )

            flash("You added a new perfume!", "info")
            return redirect(url_for("perfumes.all_perfumes"))
    else:
        flash("You need to be an administrator to enter data.", "danger")
        return redirect(url_for("main.index"))
    return render_template(
        "pages/perfume-and-type.html",
        title="New Perfume",
        form=form,
        types=mongo.db.types.find().sort("type_name"),
        new_perfume=True,
        heading="New Perfume",
    )


@perfumes.route("/perfume/<perfume_id>", methods=["GET"])
def perfume(perfume_id):
    """Returns an individual perfume

    Uses aggregation to combine perfumes and types in order
    to display details about a particular perfume.
    Includes the review form in order to allow for reviews
    to be placed over those individual perfumes.
    """

    current_perfume = mongo.db.perfumes.find_one({"_id": ObjectId(perfume_id)})
    add_review_form = AddReviewForm()
    edit_review_form = EditReviewForm()
    cur = mongo.db.perfumes.aggregate(
        [
            {
                "$lookup": {
                    "from": "users",
                    "localField": "author",
                    "foreignField": "username",
                    "as": "creator",
                }
            },
            {"$unwind": "$creator"},
            {
                "$project": {
                    "_id": "$_id",
                    "perfumeName": "$name",
                    "perfumeBrand": "$brand",
                    "perfumeDescription": "$description",
                    "date_updated": "$date_updated",
                    "perfumePicture": "$picture",
                    "isPublic": "$public",
                    "perfumeType": "$perfume_type",
                    "username": "$creator.username",
                    "firstName": "$creator.first_name",
                    "lastName": "$creator.last_name",
                    "profilePicture": "$creator.avatar",
                }
            },
            {"$match": {"_id": ObjectId(perfume_id)}},
        ]
    )
    return render_template(
        "pages/perfume.html",
        title=current_perfume["name"],
        cursor=cur,
        perfume=current_perfume,
        add_review_form=add_review_form,
        edit_review_form=edit_review_form,
    )


@perfumes.route("/perfume/<perfume_id>/delete", methods=["POST", "GET"])
@login_required
def delete_perfume(perfume_id):
    """Deletes a perfume

    Simply deletes one perfume found through its ObjectId.
    """

    if current_user.is_admin:
        mongo.db.perfumes.delete_one({"_id": ObjectId(perfume_id)})
        flash("You deleted this perfume", "success")
        return redirect(url_for("perfumes.all_perfumes"))
    flash("Not allowed", "warning")
    return redirect(url_for("perfumes.all_perfumes"))


@perfumes.route("/perfume/edit/<perfume_id>", methods=["POST", "GET"])
@login_required
def edit_perfume(perfume_id):
    """Edits an existing perfume

    If the user is an admin and the form validates, checks if there is a
    picture to be uploaded, in which case it uses the cloudinary import
    with its options to format and resize it.
    The function also replaces the http protocol rendered by cloudinary
    with https to serve them securely.
    It then updates the existing record. This existing record populates
    the form with its current values.
    """

    form = EditPerfumeForm()
    current_perfume = mongo.db.perfumes.find_one({"_id": ObjectId(perfume_id)})
    if current_user.is_admin:
        if form.validate_on_submit():
            if form.picture.data:
                picture_uploaded = upload(form.picture.data)
                # "options" is a needed parameter in order for cloudinary to
                # format the thumbnail server-side
                picture, options = cloudinary_url(
                    picture_uploaded["public_id"],
                    format="jpg",
                    crop="fill",
                    width=225,
                    height=300,
                )
                picture_link = picture.replace("http", "https")
                new_value = {
                    "$set": {
                        "brand": form.brand.data,
                        "name": form.name.data,
                        "perfume_type": form.perfume_type.data,
                        "description": form.description.data,
                        "date_updated": datetime.utcnow(),
                        "public": form.public.data,
                        "picture": picture_link,
                    }
                }
                mongo.db.perfumes.update_one(current_perfume, new_value)
                flash("You updated the perfume", "info")
                return redirect(
                    url_for(

parfumier/types/routes.py
"""Imports all Flask components, database object and forms"""
from flask import Blueprint, redirect, url_for, render_template, flash, request
from flask_login import current_user, login_required
from cloudinary.uploader import upload
from cloudinary.utils import cloudinary_url
from bson.objectid import ObjectId
from parfumier import mongo
from parfumier.types.forms import CreateTypeForm, EditTypeForm
from flask_paginate import Pagination, get_page_parameter


types = Blueprint("types", __name__)


@types.route("/type/new", methods=["POST", "GET"])
@login_required
def new_type():
    """Creates a new Perfume Type

    User has to be an admin in order to create a perfume type.
    The route simply creates a new document with the information
    passed in the form in case the form validates.
    """

    if current_user.is_admin:
        form = CreateTypeForm()
        if form.validate_on_submit():
            if form.type_picture.data:
                picture_uploaded = upload(form.type_picture.data)
                type_picture, options = cloudinary_url(
                    picture_uploaded["public_id"],
                    format="jpg",
                    crop="fill",
                    width=250,
                    height=250,
                    opacity=20,
                )
                picture_link = type_picture.replace("http", "https")
                mongo.db.types.insert(
                    {
                        "type_name": form.type_name.data,
                        "description": form.description.data,
                        "type_picture": picture_link,
                        "author": current_user.username,
                    }
                )
            else:
                mongo.db.types.insert(
                    {
                        "type_name": form.type_name.data,
                        "description": form.description.data,
                        "type_picture": (
                            "https://res.cloudinary.com/gbrachetta/"
                            "image/upload/c_scale,o_20,w_293/"
                            "v1578262574/sample.jpg"
                        ),
                        "author": current_user.username,
                    }
                )
            flash("You added a new type!", "info")
            return redirect(url_for("types.all_types"))
    else:
        flash("You need to be an administrator.", "danger")
        return redirect(url_for("main.index"))
    return render_template(
        "pages/perfume-and-type.html",
        title="New Type",
        form=form,
        new_type=True,
        heading="New Type",
    )


@types.route("/types")
def all_types():
    """Displays all types

    This route simply displays all existing types.
    It uses aggregation in order to allow for pagination.
    """
    page = request.args.get(get_page_parameter(), type=int, default=1)
    total_types = mongo.db.types.find().count()
    page_count = 8
    the_types = mongo.db.types.aggregate(
        [
            {
                "$lookup": {
                    "from": "types",
                    "localField": "type_name",
                    "foreignField": "perfume_type",
                    "as": "type",
                }
            },
            {"$unwind": "$type_name"},
            {
                "$project": {
                    "_id": "$_id",
                    "typeName": "$type_name",
                    "picture": "$type_picture",
                }
            },
            {"$sort": {"typeName": 1}},
            {"$skip": (page - 1) * page_count},
            {"$limit": page_count},
        ]
    )
    pagination = Pagination(
        per_page=8,
        page=page,
        total=total_types,
        record_name="types",
        bs_version=4,
        alignment="center",
        display_msg="Displaying <b>{start} - {end}</b>\
        {record_name} of <b>{total}</b>",
    )
    return render_template(
        "pages/types.html",
        types=the_types,
        title="Types",
        pagination=pagination,
    )


@types.route("/type/<type_id>")
def show_type(type_id):
    """Displays one type only

    This route displays the type selected using the unique ObjectId.
    """

    one_type = mongo.db.types.find_one({"_id": ObjectId(type_id)})
    return render_template(
        "pages/type.html", type=one_type, title=one_type["type_name"]
    )


@types.route("/type/<type_id>", methods=["POST"])
@login_required
def delete_type(type_id):
    """Deletes a perfume type

    This route simply deletes a perfume type matched by its id.
    It's only available to admins.
    """

    if current_user.is_admin:
        mongo.db.types.delete_one({"_id": ObjectId(type_id)})
        flash("You deleted this type", "success")
        return redirect(url_for("types.all_types"))
    flash("Not allowed", "warning")
    return redirect(url_for("types.all_types"))


@types.route("/type/edit/<type_id>", methods=["POST", "GET"])
@login_required
def edit_type(type_id):
    """Allows editing a Perfume Type

    This route finds a type by its id, assigns the current name to the hidden
    field (used to check against to avoid a false validation error) and updates
    the current data from its corresponding document in the database.
    """

    form = EditTypeForm()
    current_type = mongo.db.types.find_one({"_id": ObjectId(type_id)})
    current_type_name = mongo.db.types.find_one(
        {"_id": ObjectId(type_id)}, {"_id": 0, "type_name": 1}
    )
    form.origin_type_name.data = current_type_name["type_name"]
    current_type_value = mongo.db.types.find_one({"_id": ObjectId(type_id)})
    if current_user.is_admin:
        if form.validate_on_submit():
            if form.type_picture.data:
                picture_uploaded = upload(form.type_picture.data)
                type_picture, options = cloudinary_url(
                    picture_uploaded["public_id"],
                    format="jpg",
                    crop="fill",
                    width=250,
                    height=250,
                    opacity=20,
                )
                picture_link = type_picture.replace("http", "https")
                new_value = {
                    "$set": {
                        "type_name": form.type_name.data,
                        "description": form.description.data,
                        "type_picture": picture_link,
                    }
                }
                mongo.db.types.update_one(current_type_value, new_value)
                flash("Type has been updated", "info")
                return redirect(
                    url_for(
                        "types.show_type", type_id=current_type_value["_id"]
                    )
                )
            else:
                new_value = {
                    "$set": {
                        "type_name": form.type_name.data,
                        "description": form.description.data,
                    }
                }
            mongo.db.types.update_one(current_type_value, new_value)
            flash("Type has been updated", "info")
            return redirect(
                url_for("types.show_type", type_id=current_type_value["_id"])
            )
        form.type_name.data = current_type_value["type_name"]
        form.description.data = current_type_value["description"]
    return render_template(
        "pages/perfume-and-type.html",
        title="Edit Type",
        form=form,
        current_type=current_type,
        edit_type=True,
        heading="Edit Type",
    )

parfumier/templates/pages/about.html
{% extends "layout/base.html" %} {% block content %}

<main class="page contact-page">
    <section class="portfolio-block contact">
        <div class="container">
            <div class="heading">
                <h2 class="titles">
                    Welcome to Parfumier{% if current_user.is_authenticated %}, {{
                    current_user.username.title() }}{% endif %}!
                </h2>
            </div>
            <div class="row justify-content-center">
                <div class="col-md-8 text-center">
                    <p class="mb-5 text-left">
                        Perfume is thousands of years old, with evidence of the first perfumes
                        dating back to Ancient Egypt, Mesopotamia and Cyprus. The English word
                        "perfume" comes from the Latin per fume, meaning "through smoke."
                    </p>
                    <img class="img-fluid mb-0" src="{{ url_for("static",
                    filename="images/roman-bottle.jpg") }}" loading="lazy" width=400 height=300
                        alt="Flower Field" /><br />
                    <small>Roman cameo glass perfume-bottle, ca. 25 BCE</small>
                    <p class="my-5 text-left">
                        The Ancient Egyptians were the first to incorporate perfume into their
                        culture, followed by the ancient Chinese, Hindus, Israelites, Carthaginians,
                        Arabs, Greeks, and Romans.
                        <br />
                        The oldest perfumes ever found were discovered by archeologists in Cyprus.
                        They were more than four thousand years old. A cuneiform tablet from
                        Mesopotamia, dating back more than three thousand years, identifies a woman
                        named Tapputi as the first recorded perfume maker. But perfumes could also
                        be found in India at the time.
                        <br />
                        The 16th century saw the popularity of perfume explode in France, especially
                        among the upper classes and nobles. With help from “the perfume court,” the
                        court of Louis XV, everything got perfumed: furniture, gloves and clothing.
                        <br />
                    </p>
                    <img class="img-fluid mb-0" src="{{ url_for("static",
                    filename="images/louisXV.jpg") }}" loading="lazy" width=400 height=300 alt="Flower Field" /><br />
                    <small>Perfumed water fountain, France, 18th c.</small>
                    <p class="my-5 text-left">
                        One of the oldest uses of perfume comes from the burning of incense and
                        aromatic herbs for religious services, often the aromatic gums, frankincense
                        and myrrh gathered from trees. It did not take long, though, for people to
                        discover perfume’s romantic potential and it was used both for seduction and
                        as preparation for love-making.
                        <br />
                        Although niche perfume makers remain to cater to the very rich, perfumes
                        today enjoy widespread use. The selling of perfume, however, is no longer
                        just the purview of perfume makers. In the 20th century, clothing designers
                        began marketing their own lines of scents, and almost any celebrity with a
                        lifestyle brand can be found hawking a perfume with their name (if not
                        smell) on it.
                    </p>
                    <img class="img-fluid mb-0" src="{{ url_for("static",
                    filename="images/flower-field.jpg") }}" loading="lazy" width=600 height=300
                        alt="Flower Field" /><br />
                    <small>Lavender fields in Grasse, France</small>
                    <p class="my-5 text-left">
                        Please enjoy this website, discover perfumes, learn about what their types
                        are, leave a review and read what others have to say about them!
                    </p>
                </div>
            </div>
        </div>
    </section>
</main>

{% endblock content %}

parfumier/templates/pages/index.html
{% extends "layout/base.html" %}
{% block content %}

<main class="page contact-page">
    <section class="portfolio-block contact">
        <div class="container">
            <div class="heading">
                <h2 class=" titles">Welcome to Parfumier</h2>
                {% if current_user.is_authenticated %}
                <h3>Welcome, {{ current_user.username.title() }}!</h3>
                {% endif %}
                <p class="my-5 lead">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla distinctio nihil
                    deleniti laboriosam tempora reprehenderit autem enim et nisi iure, dignissimos
                    illum, quia maiores dolorum quae officia! Nam aperiam adipisci, doloremque quod quas
                    dolores hic voluptatibus laudantium minima architecto quo quae harum tempora, saepe,
                    veritatis veniam vero dolor earum deleniti assumenda possimus nobis. Laudantium
                    commodi reprehenderit et corporis velit cum dolores quae animi architecto ex
                    repellendus possimus voluptates dolorum nulla ad eius, dolorem maiores natus unde
                    molestiae quibusdam! Doloribus, hic voluptas. Ad doloribus sequi beatae earum
                    laborum eligendi unde. Autem laborum nemo voluptatibus minima labore ut fugiat rerum
                    maiores accusamus.
                </p>
                <img class="img-fluid mb-5" src="https://cdn.myonlinestore.eu/943d3925-6be1-11e9-a722-44a8421b9960/images/VitexNaturaWholesale%20Grasse%20Perfume%20flowers.jpg" loading="lazy" width=500 height=300 alt="Flower Field" />
            </div>
        </div>
    </section>
</main>

{% endblock content %}

parfumier/templates/pages/perfume-and-type.html
{% extends "layout/base.html" %}
{% block content %}

<main class="page contact-page">
    <section class="portfolio-block contact">
        <div class="container">
            <div class="heading">
                <h2 class="text-capitalize">{{ heading }}</h2>
            </div>
            <!-- Displays forms depending on variables passed from routes -->
            {% if new_perfume %}
                {% include "forms/new-perfume-form.html" %}
            {% elif edit_perfume %}
                {% include "forms/edit-perfume-form.html" %}
            {% elif new_type%}
                {% include "forms/new-type-form.html" %}
            {% else %}
                {% include "forms/edit-type-form.html" %}
            {% endif %}
        </div>
    </section>
</main>

{% block CKEditor %}
<script src="https://cdn.ckeditor.com/4.14.0/basic/ckeditor.js"></script>
{% endblock CKEditor %}

{% endblock content%}

parfumier/templates/pages/perfume.html
{% extends "layout/base.html" %}
{% block content %}

<main class="page project-page">
    <section class="portfolio-block project pb-0">
        <div class="container">
            <div class="heading">
                <h2>{{ perfume.name.title() }}</h2>
            </div>
            <!-- Start Perfume Cursor -->
            {% include "components/perfume-cursor.html" %}
        </div>
    </section>
</main>

<!-- Reviews -->
{% include "components/perfume-reviews.html" %}

<!-- Modals -->
{% include "modals/delete-perfume-modal.html" %}
{% include "modals/create-review-modal.html" %}
{% include "modals/delete-review-modal.html" %}
{% include "modals/edit-review-modal.html" %}
{% include "modals/login-reminder-modal.html" %}

<!-- Loads CKEditor only where needed -->
{% block CKEditor %}
    <script src="https://cdn.ckeditor.com/4.14.0/basic/ckeditor.js"></script>
{% endblock CKEditor %}

{% endblock content %}

parfumier/templates/pages/perfumes.html
{% extends "layout/base.html" %}
{% block content %}

<main class="page projets-page">
    <section class="portfolio-block projects compact-grid container">
        <!-- Search & Filter -->
        {% include "components/search-and-filter.html" %}
        <div class="container mb-4 pt-4">
            <div class="col-12 text-center mb-4">
                {% if query %}
                <a class="btn shadow-sm my-buttons purple mb-5" href="{{ url_for("perfumes.all_perfumes") }}"
                    role="button">Back to All Perfumes</a>
                {% endif %}
            </div>
            <!-- Perfume card -->
            {% include "components/perfume-card.html" %}
            <!-- Pagination -->
            <div class="col-12 text-center px-0 mt-5">
                {{ pagination.info }}
                {{ pagination.links }}
            </div>
            {% if current_user.is_admin %}
            <div class="col-12 text-center mt-4">
                <a class="btn shadow-sm my-buttons purple" href="{{ url_for("perfumes.new_perfume") }}"
                    role="button">Create New Perfume</a>
            </div>
            {% endif %}
    </section>
</main>

{% endblock content %}

parfumier/templates/pages/type.html
{% extends "layout/base.html" %}
{% block content %}

<main class="page project-page">
    <section class="portfolio-block">
        <div class="container">
            <div class="heading">
                <h2 class="text-capitalize">{{ type.type_name }}</h2>
            </div>
            <div class="row justify-content-center">
                <div class="col-12 col-md-6 info">
                    <h3>
                        <a href="{{ url_for("perfumes.perfumes_types", perfume_type=type.type_name) }}">
                            {{ type.type_name }}</a>
                    </h3>
                    <p class="card-text">{{ type.description | safe}}</p>
                    <div class="row">
                        <div class="col-4 text-left">
                            <a class="shadow-sm btn btn-sm my-buttons green"
                                href="{{ url_for("types.all_types") }}">Back</a>
                        </div>
                        <div class="col-8 text-right">
                            <!-- Delete button only if admin is the creator -->
                            {% if current_user.is_admin and current_user.username == type.author %}
                            <a href="{{ url_for("types.edit_type", type_id=type._id) }}"
                                class="btn my-buttons blue btn-sm shadow-sm">Edit</a>
                            <button type="button" class="btn my-buttons red btn-sm shadow-sm" data-toggle="modal"
                                data-target="#deleteTypeModal">Delete</button>
                            {% elif current_user.is_admin %}
                            <a href="{{ url_for("types.edit_type", type_id=type._id) }}"
                                class="btn my-buttons blue btn-sm shadow-sm">Edit</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</main>

<!-- MODAL -->
{% include "modals/delete-type-modal.html" %}

{% endblock content %}

parfumier/templates/pages/types.html
{% extends "layout/base.html" %}
{% block content %}

<main class="page projets-page">
    <section class="portfolio-block project-no-images">
        <div class="container">
            <div class="heading">
                <h2 class="text-capitalize">Perfume Types</h2>
            </div>
            <div class="row">
                {% include "components/type-cursor.html" %}
                <!-- Pagination -->
                <div class="col-12 text-center px-0 mt-5">
                    {{ pagination.info }}
                    {{ pagination.links }}
                </div>
                <!-- Displays create button only to admins -->
                {% if current_user.is_admin %}
                <div class="col-12 text-center mt-4">
                    <a href="{{ url_for("types.new_type") }}" class="btn my-buttons purple shadow-sm"
                        type="button">Create new type</a>
                </div>
                {% endif %}
            </div>
        </div>
    </section>
</main>

{% endblock content %}

parfumier/templates/pages/users.html
{% extends "layout/base.html" %}
{% block content %}

<main class="page contact-page">
    <section class="portfolio-block contact">
        <div class="container">
            <div class="heading">
                <h2 class="text-capitalize titles">{{ heading }}</h2>
            </div>
            <!-- Forms logic -->
            {% if account %}
                {% include "forms/account-form.html" %}
            {% elif login %}
                {% include "forms/login-form.html" %}
            {% elif register %}
                {% include "forms/register-form.html" %}
            {% elif reset_request %}
                {% include "forms/reset-request-form.html" %}
            {% else %}
                {% include "forms/reset-token-form.html" %}
            {% endif %}
        </div>
    </section>
</main>
{% if account %}
    {% include "modals/delete-user-modal.html" %}
{% endif %}
{% endblock content %}